// const topsters = ["Descargas parte 1/2", "Descargas parte 3", "Descargas parte 4", "Descargas parte 5", "Spotify 1", "Spotify 2", "Spotify 3", "Spotify 4", "Spotify 5", "RYM"]

// const pick = topsters[Math.floor(Math.random()*topsters.length)]
// console.log(topsters)
// console.log(pick)

const descargasUnoDos = ["Destroy All Monsters - 1974/1976", "DJ Tron - Fucking Hardcore", "DJ Vertigo - Sonic", "Doctor Head's World Tower - Flipper's Guitar", "God - The Anatomy of Addiction", "John Zorn - Naked City", "Les Rallizes Dénudés - Heavier than a Death in the Family", "Nang Nang", "SpaceGhostPurrp - VENENO", "Spiral Tribe - Tecno Terra", "telepath - Seikan Seikou", "Third Door from the Left - Face the Firing Squad", "Throbbing Gristle - CD1", "Tommy Wright III - Runnin' N Gunnin'", "Tatsuro Yamashita - Ride on Time", "Susumu Hirasawa - Aurora", "Susumu Hirasawa - Kenja no Propeller", "3 Segundos antes Da Queda - SADQ", "Aart Zwaans - Semi Hora", "Argon - Kone Kertoo", "Bogan Wytch - Nang Hexed...", "Boredoms - Super ae", "Boris Dzaneck - Boris Dzaneck", "Café Tacvba - Revés/Yo Soy", "Cindy Lee - Age of Tenderness", "Clotta Lanzetta - Fashion x Clotta", "Corviria - Psyco Analysis", "Dr. Dre - The Chronic", "Gerry and the Holograms - Gerry and the Holograms", "Hedge Wizard - More True Than Time Thought", "Blod Besvimelse x Heroin Makes Happy Collab", "John Zorn - Cobra", "The Martian - LBH-6251876: A Red Planet Compilation", "Patricia Taxxon - Fymynob", "Rainer - Petscop Soundtrack", "Pilotredsun", "Snoop Doggy Dogg - Doggystyle", "Tiny Mouse - Tiny Adventures", "Tom Ellard - 80s Cheesecake", "Vinterriket", "Wendy Carlos - Clockwork Orange", "Staruha Mha - Fires", "猫 シ Corp. - Palm Mall Mars"]

const pickUnoDos = descargasUnoDos[Math.floor(Math.random()*descargasUnoDos.length)]
console.log("Descargas [1 / 2] - - - >", pickUnoDos)

const espacio = "- - - - -"

console.log(espacio)
console.log(espacio)

const descargasTres = ["Neil Young - Harvest", "Aine O'Dwyer - Music For Church Cleaners", "Basking Sharks - Shark Island", "Bernd Kistenmacher - Romantic Times", "Bernd Kistenmacher - Wake Up in the Sun", "Bizarre Ko.Ko.Ko - 00Time", "Bugger West", "Clock-DVA - Man-Amplified", "Depressive Silence - The Darkened Empires", "DJ Sprinkles - Midtown 120 Blues", "Frank Klare - Moods", "Hot Chang - The True Totality of Chang", "Ilyas Ahmed - Between Two Skies", "In Mirrors - Escape from Berlin", "Intolerance - Intolerance", "James Ferraro - Heaven's Gate" - "James Ferraro - WENQUAN", "The Klingons - Analog-Digital", "Lead Belly - Negro Sinful Songs", "Little Richard - Little Richard", "Mark Lane - Who's Really Listening?", "Mark Shreeve - Ursa Major", "Mark Shreeve - Assassin", "Michal Turtle - Music from the Living Room", "Münn - Selbstmordwald", "Park Zero - M", "Purzum - Filosofeline", "Rhys Chatham - Factor X", "Ron Berry - Where Dark Forces Meet", "Ron Berry - The Reaper", "Sacred Tapestry - Shader", "Terry Riley - In C", "A Safe Substitute - Storm Bugs", "Thoughts on Air - Mallo Yallo", "Tuluum Shimmering - These Flowers In Dawn's Twilight At Illusion Temple", "Tuluum Shimmering - In the Great Swamp You Were Conceived", "Dungeon Rap - The Introduction (Various Artists)", "Remote Viewing: Vol. 2 (Various Artists)", "RadioNome (Various Artists)", "Antarctica (Various Artists)", "Velvet Acid Christ - Calling Ov the Dead", "Wrangler - A Situation", "X-Cetra - Stardust", "Xyl - Nuclear Winter", "Y Pants - Beat It Down", "Zanov - In Course of Time", "Fushitsusha - Pathetiqué", "Mariya Takeuchi - Variety", "Paul Robeson - Spirituals", "1992 Cool Runnings", "T.J. Hustler's Metaphysical Synthesized Orchestra - Age of Individualism", "Native Brazilian Music Vol. 1 (Various Artists)"]

const pickTres = descargasTres[Math.floor(Math.random()*descargasTres.length)]
console.log("Descargas [3] - - - >", pickTres)

console.log(espacio)
console.log(espacio)

const descargasCuatro = ["P.D. - Inweglos", "Babylon Joke - Giga", "Krankmusik - Krankmusik", "Woody Guthrie - Woody Guthrie", "Ground-Zero - Revolutionary Pekinese Opera ver 1.2.8", "No Unauthorized - Invasion", "Nomeansno - Wrong"]

const pickCuatro = descargasCuatro[Math.floor(Math.random()*descargasCuatro.length)]
console.log("Descargas [4] - - - >", pickCuatro)

console.log(espacio)
console.log(espacio)

const descargasCincoUno = ["6.3 - Humeur & Molecules", "3tot - Ich und du", "A Guy Called Gerald - 28 Gun Bad Boy", "Alan Hawkshaw - Frontiers of Science", "Alfonia Tims and His Flying Tigers - Future Funk / Uncut!", "Alice Coltrane - Divine Songs", "Allan Holdsworth: FLATTire: Music for a Non Existent Movie", "Atahualpa Yupanqui - El hombre, el paisaje y su canción", "Baffo Banfi - Galaxy My Dear", "Bernard C - Lieu Magique", "Black Kray - 700 Dagreez", "Brahim Yilmaz", "C.C.C.C. - Rocket Shrine", "Camel - Camel", "Camel - Stationary Traveller", "Camel - Rajaz", "Charlemagne Palestine - Four Manifestations on Six Elements", "Chêne noir - Chant pour le Delta, la Lune et le Soleil", "Die Synthetische Republik - Faktor D", "Elend - Les Tenebres du Dehors", "Eroc - Eroc", "The Fast Set - Untitled", "Fluxion - Bipolar Defect", "From Nursery to Misery C90", "Gachet - Elite Sounds", "The Gadgets - Gadgetree", "Galdur - Age of Legends", "Georges Rodi - Actual", "Good with Parents", "Haku - Na Mele A Ka", "Heroic Viking - Ragnarök", "Insiememusicadiversa - Insiememusicadiversa", "Isao Tomita - Snowflakes are Dancing", "Jason Lescalleet ft. Graham Lambkin - The Breadwinner", "Jason Lescalleet - The Pilgrim", "K. Yoshimatu - Commercial Romanticists", "K. Yoshimatu - Sepia Reminiscence", "Kallous Boys - Kick It", "Karlheinz Stockhausen - Hymnen", "Key Sounds Label - Kanon Original Soundtrack", "Kitaro - Ten Kai", "Konk - Jams", "L.A.S.'s Crime - Inanitas", "La Peste - HL 026", "Lauri Paisley - Skywords", "Lord Nelson - Ah, Ha", "VICKI LEEKX - VICKI LEEKX", "MACROBLANK", "Merci la nuit - Merci la nuit", "Michael Garrison - In the Regions of Sunreturn", "Moebius", "Mokira - Cliphop", "Moon Wheel", "Nine Circles - Nine Circles", "Nova - Terranova", "NSRD - Kunsendorfs un Osendovskis", "Omni Trio The Deepest Cut Vol. 1", "on4road - In Rainbow Roads", "Open Graves Style - Fear", "Peste Noire - La Sanie des siècles - Panégyrique de la dégénérescence", "Pink Industry - Low Technology", "Plug - Drum 'N' Bass for Papa", "Pola - Pola Meets Lyrica", "Pure - Fetor", "Raquin", "Renaissance - Renaissance", "Reynols - Polos Mosco", "runescape.wav2", "Salaried Man Club - Gray Cross", "Salaried Man Club", "Sines of Exquisite Pleasure - Music for Hospitals", "Skee Mask - Compro", "Sumo Jungle Grandeur", "The Sperm - Shh!", "Steve Roden - Light Forms", "Vangelis - Blade Runner (Esper Edition)", "Out of Standard Deutschland Vol. 1 (Various Artists)"]

const descargasCincoDos = ["Berthold Weis Band / Confidentiel Périodique", "Risky Business Soundtrack", "Vivian Stanshall - Sir Henry at Rawlinson End", "Walrus", "The Wicked Farleys - Make It It", "Bacchia Neraida", "Mahk - LV", "Yuri Morozov - The Inexplicable", "Battle Garegga OST", "Joe Hisashi", "Susumu Hirasawa - PHONON LIVE", "9.0Megathrust", "Nobue Kawana", "NEWS AT 11", "Ecophony Rinne", "Sharpnel vs Project Gabbangelion"]

const pickCincoUno = descargasCincoUno[Math.floor(Math.random()*descargasCincoUno.length)]
console.log("Descargas [5.1] - - - >", pickCincoUno)

const pickCincoDos = descargasCincoDos[Math.floor(Math.random()*descargasCincoDos.length)]
console.log("Descargas [5.2] - - - >", pickCincoDos)

console.log(espacio)
console.log(espacio)

const SpotifyOne = ["2003 Toyota Corolla", "Autechre - Tri Repetae", "Aziza Jalal", "black midi - Schlagenheim", "Mos Def & Talib Kwani - Black Star", "Bowery Electric - Beat", "Butthole Surfers - Psychic... Powerless... Another Man's Sac", "Carambolage", "Carly Rae Jepsen - Emotion", "Charly García - Say No More", "Cheshyre", "Cos - Viva Boma", "Daniel Johnston - Yip Jump Music", "Daniel Johnston - 1990", "Dead Kennedys - Frankenchrist", "Death - Human", "Depeche Mode - Violator", "DJ Screw - 3 in the Mornin' Part Two", "Don Salsa - Koolaide Moustache in Jonestown", "Doris Norton - Artificial Intelligence", "Super Discount", "Flema (Yin Yang)", "Frank Sinatra - Sings for Only the Lonely", "Frank Sinatra - Watertown", "German Shepherds - Music for Sick Queers", "Gil-Scott Heron - Pieces of a Man", "Giradioses - Dormitorio", "Haruomi Hosono - HOSONO HOUSE", "Hella - Hold Your Horse Is", "James Ferraro - Far Side Virtual", "Javiera Mena - Esquemas juveniles", "Lalleeshwari", "Lily Chou-Chou", "Spinetta - Kamikaze", "Manic Street Preachers - The Holy Bible", "Massive Attack - Blue Lines", "Mercedes Sosa - Con Sabor a Mercedes Sosa", "Michael Hoenig - Departure from the Northern Wasteland", "Milton Nascimento - Milton", "Milton Nascimento - Minas", "Milton Nascimento - Gerais", "Narcosis - Primera Dosis", "Nine Inch Nails - The Fragile", "Nortfalke - Atmosfeer", "Offermose - Stilhedens Tarn", "Paraf", "Philip Glass - Koyaanisqatsi", "Playboi Carti - Die Lit", "Polvo - Exploded Drawing", "The Product - Alive Again", "PSY - Psy from the Psycho World!", "Ross from Friends - Tread", "Rush - Moving Pictures", "Severed Heads - City Slab Horror", "Sheena Ringo (Taza)", "Sonic Dragolgo - My Sweet Honey Bunny", "Sparks - Kimono My Dear", "The Stalin - Stop Jap", "Nocturbulous Behavior - The Mix", "Type O Negative - Bloody Kisses", "The United States of America", "Van Morrison - Astral Weeks", "Yasuo Sugibayashi - The Mask of the Imperial Family", "ZaZa", "2+2=5, Into the Future...", "Angelo Badalamenti - Twin Peaks OST", "Automatic - Signal", "Biosphere - Substrata", "Belbury Poly - The Willows", "Brian Hodgson - KPM 1000", "Brian Eno - Ambient 4: On Land", "Ceres & Calypso", "Catherine Mercy", "The Cat's Miaow 94 - 98", "Cluster & Eno", "Croatian Amor - Genitalia Garden", "DAF - DAF", "Delroy Edwards - Hangin' at the Beach", "Detachments - Detachments", "Disasterpiece - Level", "Diseño Corbusier", "DJ Rozwell", "Dr. Alimantado - Best Dressed Chicken in Town"]

const pickSpotifyOne = SpotifyOne[Math.floor(Math.random()*SpotifyOne.length)]
console.log("Spotify [1] - - - >", pickSpotifyOne)

console.log(espacio)
console.log(espacio)

const SpotifyTwoOne = ["Crippled Black Phoenix - I, Vigilante", "Enoch Light - Spaced Out", "Erykah Badu - Mama's Gun", "Eviatar Banai", "Faust - So Far", "Felix Kubin - Matki Wandalki", "Filmmaker - Somber Realm", "Freshly Wrapped Candles - Dark Side of the Christmas...", "Gabriela - Detrás del Sol", "The Garden - HORSESHIT ON ROUTE 66", "Gary Numan - Telekon", "Giant Claw - Soft Channel", "Graham Lambkin - Salmon Run", "Guided by Voices - Bee Thousand", "Hackle - GUNSMITH THA MIXTAPE", "Hante. - Morning Tsunami", "Herb Alpert and the Tijuana Brass - !!Going Places!!", "Hi-C - High the Lonestarr Mixtape", "Hiro Yanagida - Milk Time", "Home - Odyssey", "Horse Lords - The Common Task", "Horse Lords - Comradely Objects", "Hugo Montenegro - Moog Power", "The Human League - Hysteria", "The Human League - Dare!", "Internal Rot - Mental Hygiene", "Irving Joseph - Murder, Inc.", "Isaac Hayes - Shaft", "James Chance & the Contortions - The Flesh is Weak", "Jean C. Roche - Birds of Venezuela", "The Jesus and Mary Chain - Psychocandy", "The Jesus Lizard - Goat", "João Gilberto - Chega Da Saudade", "Julee Cruise - Floating into the Night", "K2 - Demise Symphonika", "Kaleidoscope - Tangerine Dream", "Kasabian", "Kyuss - Welcome to Sky Valley", "Lena Platonos - Sun Masks", "Shleu Shleu - Tete Chauve", "Lift to Experience - The Texas-Jerusalem Crossroads", "Lil B - God's Father", "Los Kjarkas - Canto a la Mujer de Mi Pueblo", "Lou Champagne System - No Visible Means", "Mac DeMarco - Salad Days", "Machine Girl - WLFGRL", "Magic Sword - Volume 1", "The Magnetic Fields - 69 Love Songs", "The Mall - Zone", "Martial Canterel - You Today", "Martin Dupont - Sleep is a Luxury", "Martin Dupont - Just Because...", "MGMT - Little Dark Age", "The Moog Cookbook", "The Miseducation of Ms. Lauryn Hill", "Dios y la Mata de Lulo", "Nonlocal Forecast - Bubble Universe!", "Nuno Canavarro - Plux Quba", "Off the Meds - Off the Meds", "Pavement - Wowee Zowee", "Peligrosos Gorriones", "Peter Tosh - Legalize It", "Pink Siifu - NEGRO", "Plenamente - Inevitable", "Polyrock", "Prince Far I - Message from the King", "Radio Futura - Radio Futura", "Rat at Rat R - Amer$ide: Rock 'N' Roll is Dead / Long Live at Rat at Rat R", "Rozi Plain - Prize", "Sade - Love Deluxe", "Satellite Young", "Severed Heads - Clean", "The Specials (Ska)", "The Steve Howe Album", "Supermax - World of Today", "Swing Slow", "Thomas Leer & Robert Rental - The Bridge", "T.Rex - Electric Warrior", "Ulk - This Divine Shelter"]

const SpotifyTwoTwo = ["Lask", "VHS Glitch - Evil Technology", "Wilco - Yankee Hotel Foxtrot", "Willie Colón & Rubén Blades - Siembra", "Wipers - Youth of America", "Wooden Veil", "Yukihiro Takahashi - Neuromantic", "Yura Yura Teikaku - Hollow Me (El álbum de los tubos azules con fondo rosa)", "Zazou, Bikaye, Cy1 - Noir et Blanc", "Y.2089"]

const pickSpotifyTwoOne = SpotifyTwoOne[Math.floor(Math.random()*SpotifyTwoOne.length)]
console.log("Spotify [2.1] - - - >", pickSpotifyTwoOne)

const pickSpotifyTwoTwo = SpotifyTwoTwo[Math.floor(Math.random()*SpotifyTwoTwo.length)]
console.log("Spotify [2.2] - - - >", pickSpotifyTwoTwo)

console.log(espacio)
console.log(espacio)