// const topsters = ["Descargas parte 1/2", "Descargas parte 3", "Descargas parte 4", "Descargas parte 5", "Spotify 1", "Spotify 2", "Spotify 3", "Spotify 4", "Spotify 5", "RYM"]

// const pick = topsters[Math.floor(Math.random()*topsters.length)]
// console.log(topsters)
// console.log(pick)

const descargasUnoDos = ["Destroy All Monsters - 1974/1976", "DJ Tron - Fucking Hardcore", "DJ Vertigo - Sonic", "Doctor Head's World Tower - Flipper's Guitar", "God - The Anatomy of Addiction", "John Zorn - Naked City", "Les Rallizes Dénudés - Heavier than a Death in the Family", "Nang Nang", "SpaceGhostPurrp - VENENO", "Spiral Tribe - Tecno Terra", "telepath - Seikan Seikou", "Third Door from the Left - Face the Firing Squad", "Throbbing Gristle - CD1", "Tommy Wright III - Runnin' N Gunnin'", "Tatsuro Yamashita - Ride on Time", "Susumu Hirasawa - Aurora", "Susumu Hirasawa - Kenja no Propeller", "3 Segundos antes Da Queda - SADQ", "Aart Zwaans - Semi Hora", "Argon - Kone Kertoo", "Bogan Wytch - Nang Hexed...", "Boredoms - Super ae", "Boris Dzaneck - Boris Dzaneck", "Café Tacvba - Revés/Yo Soy", "Cindy Lee - Age of Tenderness", "Clotta Lanzetta - Fashion x Clotta", "Corviria - Psyco Analysis", "Dr. Dre - The Chronic", "Gerry and the Holograms - Gerry and the Holograms", "Hedge Wizard - More True Than Time Thought", "Blod Besvimelse x Heroin Makes Happy Collab", "John Zorn - Cobra", "The Martian - LBH-6251876: A Red Planet Compilation", "Patricia Taxxon - Fymynob", "Rainer - Petscop Soundtrack", "Pilotredsun", "Snoop Doggy Dogg - Doggystyle", "Tiny Mouse - Tiny Adventures", "Tom Ellard - 80s Cheesecake", "Vinterriket", "Wendy Carlos - Clockwork Orange", "Staruha Mha - Fires", "猫 シ Corp. - Palm Mall Mars"]

const pickUnoDos = descargasUnoDos[Math.floor(Math.random()*descargasUnoDos.length)]
console.log("Descargas [1 / 2] - - - >", pickUnoDos)

const espacio = "- - - - -"

console.log(espacio)
console.log(espacio)

const descargasTres = ["Neil Young - Harvest", "Aine O'Dwyer - Music For Church Cleaners", "Basking Sharks - Shark Island", "Bernd Kistenmacher - Romantic Times", "Bernd Kistenmacher - Wake Up in the Sun", "Bizarre Ko.Ko.Ko - 00Time", "Bugger West", "Clock-DVA - Man-Amplified", "Depressive Silence - The Darkened Empires", "DJ Sprinkles - Midtown 120 Blues", "Frank Klare - Moods", "Hot Chang - The True Totality of Chang", "Ilyas Ahmed - Between Two Skies", "In Mirrors - Escape from Berlin", "Intolerance - Intolerance", "James Ferraro - Heaven's Gate" - "James Ferraro - WENQUAN", "The Klingons - Analog-Digital", "Lead Belly - Negro Sinful Songs", "Little Richard - Little Richard", "Mark Lane - Who's Really Listening?", "Mark Shreeve - Ursa Major", "Mark Shreeve - Assassin", "Michal Turtle - Music from the Living Room", "Münn - Selbstmordwald", "Park Zero - M", "Purzum - Filosofeline", "Rhys Chatham - Factor X", "Ron Berry - Where Dark Forces Meet", "Ron Berry - The Reaper", "Sacred Tapestry - Shader", "Terry Riley - In C", "A Safe Substitute - Storm Bugs", "Thoughts on Air - Mallo Yallo", "Tuluum Shimmering - These Flowers In Dawn's Twilight At Illusion Temple", "Tuluum Shimmering - In the Great Swamp You Were Conceived", "Dungeon Rap - The Introduction (Various Artists)", "Remote Viewing: Vol. 2 (Various Artists)", "RadioNome (Various Artists)", "Antarctica (Various Artists)", "Velvet Acid Christ - Calling Ov the Dead", "Wrangler - A Situation", "X-Cetra - Stardust", "Xyl - Nuclear Winter", "Y Pants - Beat It Down", "Zanov - In Course of Time", "Fushitsusha - Pathetiqué", "Mariya Takeuchi - Variety", "Paul Robeson - Spirituals", "1992 Cool Runnings", "T.J. Hustler's Metaphysical Synthesized Orchestra - Age of Individualism", "Native Brazilian Music Vol. 1 (Various Artists)"]

const pickTres = descargasTres[Math.floor(Math.random()*descargasTres.length)]
console.log("Descargas [3] - - - >", pickTres)

console.log(espacio)
console.log(espacio)

const descargasCuatro = ["P.D. - Inweglos", "Babylon Joke - Giga", "Krankmusik - Krankmusik", "Woody Guthrie - Woody Guthrie", "Ground-Zero - Revolutionary Pekinese Opera ver 1.2.8", "No Unauthorized - Invasion", "Nomeansno - Wrong"]

const pickCuatro = descargasCuatro[Math.floor(Math.random()*descargasCuatro.length)]
console.log("Descargas [4] - - - >", pickCuatro)

console.log(espacio)
console.log(espacio)

const descargasCincoUno = ["6.3 - Humeur & Molecules", "3tot - Ich und du", "A Guy Called Gerald - 28 Gun Bad Boy", "Alan Hawkshaw - Frontiers of Science", "Alfonia Tims and His Flying Tigers - Future Funk / Uncut!", "Alice Coltrane - Divine Songs", "Allan Holdsworth: FLATTire: Music for a Non Existent Movie", "Atahualpa Yupanqui - El hombre, el paisaje y su canción", "Baffo Banfi - Galaxy My Dear", "Bernard C - Lieu Magique", "Black Kray - 700 Dagreez", "Brahim Yilmaz", "C.C.C.C. - Rocket Shrine", "Camel - Camel", "Camel - Stationary Traveller", "Camel - Rajaz", "Charlemagne Palestine - Four Manifestations on Six Elements", "Chêne noir - Chant pour le Delta, la Lune et le Soleil", "Die Synthetische Republik - Faktor D", "Elend - Les Tenebres du Dehors", "Eroc - Eroc", "The Fast Set - Untitled", "Fluxion - Bipolar Defect", "From Nursery to Misery C90", "Gachet - Elite Sounds", "The Gadgets - Gadgetree", "Galdur - Age of Legends", "Georges Rodi - Actual", "Good with Parents", "Haku - Na Mele A Ka", "Heroic Viking - Ragnarök", "Insiememusicadiversa - Insiememusicadiversa", "Isao Tomita - Snowflakes are Dancing", "Jason Lescalleet ft. Graham Lambkin - The Breadwinner", "Jason Lescalleet - The Pilgrim", "K. Yoshimatu - Commercial Romanticists", "K. Yoshimatu - Sepia Reminiscence", "Kallous Boys - Kick It", "Karlheinz Stockhausen - Hymnen", "Key Sounds Label - Kanon Original Soundtrack", "Kitaro - Ten Kai", "Konk - Jams", "L.A.S.'s Crime - Inanitas", "La Peste - HL 026", "Lauri Paisley - Skywords", "Lord Nelson - Ah, Ha", "VICKI LEEKX - VICKI LEEKX", "MACROBLANK", "Merci la nuit - Merci la nuit", "Michael Garrison - In the Regions of Sunreturn", "Moebius", "Mokira - Cliphop", "Moon Wheel", "Nine Circles - Nine Circles", "Nova - Terranova", "NSRD - Kunsendorfs un Osendovskis", "Omni Trio The Deepest Cut Vol. 1", "on4road - In Rainbow Roads", "Open Graves Style - Fear", "Peste Noire - La Sanie des siècles - Panégyrique de la dégénérescence", "Pink Industry - Low Technology", "Plug - Drum 'N' Bass for Papa", "Pola - Pola Meets Lyrica", "Pure - Fetor", "Raquin", "Renaissance - Renaissance", "Reynols - Polos Mosco", "runescape.wav2", "Salaried Man Club - Gray Cross", "Salaried Man Club", "Sines of Exquisite Pleasure - Music for Hospitals", "Skee Mask - Compro", "Sumo Jungle Grandeur", "The Sperm - Shh!", "Steve Roden - Light Forms", "Vangelis - Blade Runner (Esper Edition)", "Out of Standard Deutschland Vol. 1 (Various Artists)"]

const descargasCincoDos = ["Berthold Weis Band / Confidentiel Périodique", "Risky Business Soundtrack", "Vivian Stanshall - Sir Henry at Rawlinson End", "Walrus", "The Wicked Farleys - Make It It", "Bacchia Neraida", "Mahk - LV", "Yuri Morozov - The Inexplicable", "Battle Garegga OST", "Joe Hisashi", "Susumu Hirasawa - PHONON LIVE", "9.0Megathrust", "Nobue Kawana", "NEWS AT 11", "Ecophony Rinne", "Sharpnel vs Project Gabbangelion"]

const pickCincoUno = descargasCincoUno[Math.floor(Math.random()*descargasCincoUno.length)]
console.log("Descargas [5.1] - - - >", pickCincoUno)

const pickCincoDos = descargasCincoDos[Math.floor(Math.random()*descargasCincoDos.length)]
console.log("Descargas [5.2] - - - >", pickCincoDos)

console.log(espacio)
console.log(espacio)

const SpotifyOne = ["2003 Toyota Corolla", "Autechre - Tri Repetae", "Aziza Jalal", "black midi - Schlagenheim", "Mos Def & Talib Kwani - Black Star", "Bowery Electric - Beat", "Butthole Surfers - Psychic... Powerless... Another Man's Sac", "Carambolage", "Carly Rae Jepsen - Emotion", "Charly García - Say No More", "Cheshyre", "Cos - Viva Boma", "Daniel Johnston - Yip Jump Music", "Daniel Johnston - 1990", "Dead Kennedys - Frankenchrist", "Death - Human", "Depeche Mode - Violator", "DJ Screw - 3 in the Mornin' Part Two", "Don Salsa - Koolaide Moustache in Jonestown", "Doris Norton - Artificial Intelligence", "Super Discount", "Flema (Yin Yang)", "Frank Sinatra - Sings for Only the Lonely", "Frank Sinatra - Watertown", "German Shepherds - Music for Sick Queers", "Gil-Scott Heron - Pieces of a Man", "Giradioses - Dormitorio", "Haruomi Hosono - HOSONO HOUSE", "Hella - Hold Your Horse Is", "James Ferraro - Far Side Virtual", "Javiera Mena - Esquemas juveniles", "Lalleeshwari", "Lily Chou-Chou", "Spinetta - Kamikaze", "Manic Street Preachers - The Holy Bible", "Massive Attack - Blue Lines", "Mercedes Sosa - Con Sabor a Mercedes Sosa", "Michael Hoenig - Departure from the Northern Wasteland", "Milton Nascimento - Milton", "Milton Nascimento - Minas", "Milton Nascimento - Gerais", "Narcosis - Primera Dosis", "Nine Inch Nails - The Fragile", "Nortfalke - Atmosfeer", "Offermose - Stilhedens Tarn", "Paraf", "Philip Glass - Koyaanisqatsi", "Playboi Carti - Die Lit", "Polvo - Exploded Drawing", "The Product - Alive Again", "PSY - Psy from the Psycho World!", "Ross from Friends - Tread", "Rush - Moving Pictures", "Severed Heads - City Slab Horror", "Sheena Ringo (Taza)", "Sonic Dragolgo - My Sweet Honey Bunny", "Sparks - Kimono My Dear", "The Stalin - Stop Jap", "Nocturbulous Behavior - The Mix", "Type O Negative - Bloody Kisses", "The United States of America", "Van Morrison - Astral Weeks", "Yasuo Sugibayashi - The Mask of the Imperial Family", "ZaZa", "2+2=5, Into the Future...", "Angelo Badalamenti - Twin Peaks OST", "Automatic - Signal", "Biosphere - Substrata", "Belbury Poly - The Willows", "Brian Hodgson - KPM 1000", "Brian Eno - Ambient 4: On Land", "Ceres & Calypso", "Catherine Mercy", "The Cat's Miaow 94 - 98", "Cluster & Eno", "Croatian Amor - Genitalia Garden", "DAF - DAF", "Delroy Edwards - Hangin' at the Beach", "Detachments - Detachments", "Disasterpiece - Level", "Diseño Corbusier", "DJ Rozwell", "Dr. Alimantado - Best Dressed Chicken in Town"]

const pickSpotifyOne = SpotifyOne[Math.floor(Math.random()*SpotifyOne.length)]
console.log("Spotify [1] - - - >", pickSpotifyOne)

console.log(espacio)
console.log(espacio)

const SpotifyTwoOne = ["Crippled Black Phoenix - I, Vigilante", "Enoch Light - Spaced Out", "Erykah Badu - Mama's Gun", "Eviatar Banai", "Faust - So Far", "Felix Kubin - Matki Wandalki", "Filmmaker - Somber Realm", "Freshly Wrapped Candles - Dark Side of the Christmas...", "Gabriela - Detrás del Sol", "The Garden - HORSESHIT ON ROUTE 66", "Gary Numan - Telekon", "Giant Claw - Soft Channel", "Graham Lambkin - Salmon Run", "Guided by Voices - Bee Thousand", "Hackle - GUNSMITH THA MIXTAPE", "Hante. - Morning Tsunami", "Herb Alpert and the Tijuana Brass - !!Going Places!!", "Hi-C - High the Lonestarr Mixtape", "Hiro Yanagida - Milk Time", "Home - Odyssey", "Horse Lords - The Common Task", "Horse Lords - Comradely Objects", "Hugo Montenegro - Moog Power", "The Human League - Hysteria", "The Human League - Dare!", "Internal Rot - Mental Hygiene", "Irving Joseph - Murder, Inc.", "Isaac Hayes - Shaft", "James Chance & the Contortions - The Flesh is Weak", "Jean C. Roche - Birds of Venezuela", "The Jesus and Mary Chain - Psychocandy", "The Jesus Lizard - Goat", "João Gilberto - Chega Da Saudade", "Julee Cruise - Floating into the Night", "K2 - Demise Symphonika", "Kaleidoscope - Tangerine Dream", "Kasabian", "Kyuss - Welcome to Sky Valley", "Lena Platonos - Sun Masks", "Shleu Shleu - Tete Chauve", "Lift to Experience - The Texas-Jerusalem Crossroads", "Lil B - God's Father", "Los Kjarkas - Canto a la Mujer de Mi Pueblo", "Lou Champagne System - No Visible Means", "Mac DeMarco - Salad Days", "Machine Girl - WLFGRL", "Magic Sword - Volume 1", "The Magnetic Fields - 69 Love Songs", "The Mall - Zone", "Martial Canterel - You Today", "Martin Dupont - Sleep is a Luxury", "Martin Dupont - Just Because...", "MGMT - Little Dark Age", "The Moog Cookbook", "The Miseducation of Ms. Lauryn Hill", "Dios y la Mata de Lulo", "Nonlocal Forecast - Bubble Universe!", "Nuno Canavarro - Plux Quba", "Off the Meds - Off the Meds", "Pavement - Wowee Zowee", "Peligrosos Gorriones", "Peter Tosh - Legalize It", "Pink Siifu - NEGRO", "Plenamente - Inevitable", "Polyrock", "Prince Far I - Message from the King", "Radio Futura - Radio Futura", "Rat at Rat R - Amer$ide: Rock 'N' Roll is Dead / Long Live at Rat at Rat R", "Rozi Plain - Prize", "Sade - Love Deluxe", "Satellite Young", "Severed Heads - Clean", "The Specials (Ska)", "The Steve Howe Album", "Supermax - World of Today", "Swing Slow", "Thomas Leer & Robert Rental - The Bridge", "T.Rex - Electric Warrior", "Ulk - This Divine Shelter"]

const SpotifyTwoTwo = ["Lask", "VHS Glitch - Evil Technology", "Wilco - Yankee Hotel Foxtrot", "Willie Colón & Rubén Blades - Siembra", "Wipers - Youth of America", "Wooden Veil", "Yukihiro Takahashi - Neuromantic", "Yura Yura Teikaku - Hollow Me (El álbum de los tubos azules con fondo rosa)", "Zazou, Bikaye, Cy1 - Noir et Blanc", "Y.2089"]

const pickSpotifyTwoOne = SpotifyTwoOne[Math.floor(Math.random()*SpotifyTwoOne.length)]
console.log("Spotify [2.1] - - - >", pickSpotifyTwoOne)

const pickSpotifyTwoTwo = SpotifyTwoTwo[Math.floor(Math.random()*SpotifyTwoTwo.length)]
console.log("Spotify [2.2] - - - >", pickSpotifyTwoTwo)

console.log(espacio)
console.log(espacio)

const SpotifyThreeOne = ["Aerial M", "Agent Side Grinder", "AG Geige - Trick Beat", "Amy Winehouse - Back to Black", "Anri - Timely!!", "Area - Caution Radiation Area", "Art Blakey & The Jazz Messengers - Mosaic", "Artie Shaw - Plays an Album of Popular Music", "The Art of Noise - (Who's Afraid Of) The Art Of Noise?", "Asphixiation - What is this thing called Disco?", "Astor Piazzolla - Libertango", "Autumn - Synthesize", "Babatunde Olatunji - Soul Makossa", "Bal Paré - Hamburg Paris Catania", "Beau Wanzer - Untitled", "Bo Diddley - The Black Gladiator", "Booker T. & the MG's - Melting Pot", "Bootsy Collins - Stretchin Out In Bootsy's Rubber Band", "Boy Harsher - Yr Body Is Nothing", "The Brothers Johnson - Look Out For #1", "Burzum - Hlidskjalf", "Cabaret Voltaire - The Voice Of America", "Ceramic Hello - The Absence of a Canary", "Chapterhouse - Whirlpool", "Charles Cohen - Brother I Prove You Wrong", "Chris Watson - Outside the Circle of Fire", "Chrome - Alien Soundtracks", "Cybotron", "Fauli Til Dauli", "Dakila", "Dan Deacon - Mystic Familiar", "Daryl Hall & John Oates - Abandoned Luncheonette", "David Chesworth - 50 Synthesizer Greats", "Death in June - But, What Ends When the Symbols Shatter?", "De La Soul - 3 Feet High and Rising", "Demon Fuzz - Afreaka!", "Die Gesunden", "DJ Kridlokk - UG Solo", "don armando's 2nd ave rhumba band - Deputy of Love", "Drowning the Light - Haunter of the Deep", "Embryo - Rocksession", "Etta James - At Last!", "Fleet Foxes", "Föllakzoid - III", "Forgotten Pathways - Shrouded in Mystery", "Freddie Slack's Boogie Woogie", "Fred Wesley & The Horny Horns - A Blow For Me, A Toot To You", "Gabe Gurnsey - Diablo", "Garçons - Divorce", "George Clinton - Computer Games", "Gezan - ANOCHI", "Ghetto Brothers - Power Fuerza", "Giacinto Scelsi - Natura renovatur", "Grauzone", "Green Unleaded are the Product", "Helena Hauff - Discreet Desires", "Hiiragi Fukuda - Seacide", "Hüsker Dü - Zen Arcade", "Ike & Tina Turner - Come Together-Workin' Together", "Interacción - Extensión de los Significados", "The Isley Brothers - 3+3", "Jaakko Kangosjärvi - Ihmeellinen Luonto", "Jan Hammer - Escape From Television", "Jessica Bailiff", "J.J. Cale - Naturally", "Joe Meek - I Hear A New World", "John Carpenter - Lost Themes", "John Frusciante - Niandra LaDes And Usually Just A T-Shirt", "John Grant - Love Is Magic", "Jon Appleton - Human Music", "Jorge Ben Jor - Jorge Ben", "Jorge Ben Jor - A Tabua De Esmeralda", "Juega el Loco - Esto No Es"]

const SpotifyThreeTwo = ["Julie's Haircut - In The Silence Electric", "Jyl", "katie dey - flood network", "Kid Creole & The Coconuts - Tropical Gangsters", "Kreng - Grimoire", "Lamp - For Lovers", "Latin Playboys", "LCD Soundsystem - 45:33", "Los Iniciados - la marca de anubis", "Love - Forever Changes", "Marconi Union - Dead Air", "master boot record - Direct Memory Access", "Matchess - Sacracorpa", "Max Corbacho - Ars Lucis", "Meat Beat Manifesto - 99%", "Mimilocos - trulepa", "Newfound Interest In Connecticut - Tell Me About the Long Dark Path Home", "Niagara", "nik raicevic - Head", "Niño Mercurio - harmony korine", "No Trend - Too Many Humans", "Nujabes - Modal Soul", "Orchestral Manoeuvres in the Dark - Architecture And Morality", "Paco de Lucía - Entre Dos Aguas", "Penguin Cafe Orchestra - Music From The Penguin Cafe", "Philip Glass - Einstein on the Beach", "Pig Destroyer - Terrifyer", "Plone - For Beginner Piano", "The Pop Group - For How Much Longer Do We Tolerate Mass Murder?", "The Prima Donnas - drugs sex and discotheques", "Profil - Profil", "Richard Pinhas - L'Ethique", "Rival Schools - United By Fate", "Robson Jorge - Robson Jorge e Lincoln Olivetti", "Romano Musumarra - Automat", "Semiramis - Dedicato a Frazz", "Serge Gainsbourg - Histoire de Melody Nelson", "Shame - Food For Worms", "Silver Jews - American Water", "Silvia Kastel - Air Lows", "Software - Digital-Dance", "Steve Roach - Traveler", "Swamp Dogg - Total Destruction to Your Mind", "Tim Blake - New Jerusalem", "Tim Maia 1971", "Tommi Stumpff - Zu spät ihr Scheisser", "Travesti - Áxito", "Vapora - Hologram Plaza 2", "Ventre de biche - Viens Mourir", "Was (Not Was) - Out Come the Freaks", "Wayne Shorter - Speak No Evil", "Wayne Shorter - JuJu", "Xavier Cugat and His Waldorf-Astoria Orchestra - A Xavier Cugat Album of Latin American Music", "Yma Sumac - Voice of the Xtabay"]

const pickSpotifyThreeOne = SpotifyThreeOne[Math.floor(Math.random()*SpotifyThreeOne.length)]
console.log("Spotify [3.1] - - - >", pickSpotifyThreeOne)

const pickSpotifyThreeTwo = SpotifyThreeTwo[Math.floor(Math.random()*SpotifyThreeTwo.length)]
console.log("Spotify [3.2] - - - >", pickSpotifyThreeTwo)

console.log(espacio)
console.log(espacio)

const SpotifyFourOne = ["2 Minutos - Valentín Alsina", "Alain Bashung - L'Imprudence", "Arthur Russell - World of Echo", "The Band", "Barbara chanson Jacques Brel", "Bejalvin - BEJIBLE", "Big Brother... - Cheap Thrills", "Bon Iver - For Emma, Forever Ago", "Burzum - Daudi Baldrs", "Celtic Frost - Monotheist", "Charlie Megira & the Modern Dance Club - Love Police", "Chromatics - Night Drive", "Conditioner Disco Group", "Cunninlynguists - A Piece of Strange", "Daniel Darc - Crèvecoeur", "Daryl Hall & John Oates - H2O", "Das Kabinette - Spy Thriller", "Deep Magic - Closed Eyes", "d'Eon - Music for Keyboards, vol. VI", "Dreamers Cloth - Vitrospection 2008-2009", "Music from Ys", "Flamen Dialis - Symptome Dei", "Floor", "Françoise Hardy - L'amitie", "Franco Leprino - Integrati... Disintegrati...", "Franek Kimono", "Genesis Owusu", "Georges Brassens Nº1", "Georges Brassens Nº13", "Gerhard Trede - Montage", "Guzzard - Quiet, Fast, In a Hurry", "Handsomeboy Technique - Adelie Land", "Hieroglyphic Being - The Discos of Imhotep", "Iron Curtain - Desertion 1982-1988", "Jacno", "Japan - Adolescent Sex", "Jim James - Eternally Even", "Jorge Ben Jor - Força Bruta", "Jorge Ben Jor - Africa Brasil", "Julien Clerc", "Jun Fukamachi - Quark", "Klaus Schulze - Mirage", "Laura Nyro - Christmas and...", "Laura Nyro - Gonna Take a Miracle", "Läuten der Seele", "Lightwave - Tycho Brahe", "Lil Yachty - Let's Start Here.", "Lindstrom & Prins Thomas", "Lives of Angels - Elevator to Eden", "Lowercase - Kill the Lights", "Lowercase - The Going Away Present", "Marie Davidson - Adieux au dancefloor", "Marie Davidson - Working Class Woman", "MF DOOM - Operation: Doomsday", "MF DOOM - MM..FOOD", "Mecano", "Michael Kiwanuka", "Morphine - Good", "Motohiko Hamase - #Notes of Forestry", "Nico - Desertshore", "Nik Colk Void - Bucked Up Space", "NO ZU - Afterlife", "Offlaga Disco Pax - Socialismo Tascabile", "Otay:onii - Dream Hacker", "Palm - Nicks and Gazes", "Patrick Vian - Bruits et Temps Analogues", "Phideaux - Formaldehyde", "Pink Turns Blue - If Two Worlds Kiss", "Pond - Planetenwind", "Portishead - Third", "Proux - Back By Popular Demand", "Puzzle - The Rotten Opera", "Rainbowdragoneyes - The Secret Mirror", "Ray Barretto - Power", "Roger Eno - Voices", "Roisin Machine", "Saul Williams - The Inevitable Rise...", "Serge Gainsbourg - Initials B.B.", "Sérgio Sampaio", "Sex Pistols - Never Mind the Bollocks", "Simon & Garfunkel - Sounds of Silence", "Simon & Garfunkel - Bookends"]

const SpotifyFourTwo = ["Simon & Garfunkel - Bridge Over Troubled Water", "Tomorrow's Gift", "Tuxedomoon - Half-Mute", "UT", "Vanligt Folk - Hambo", "Weather Report - Mr. Gone", "Headhunterz & Wildstylez - Project One", "Space, Energy & Light: Electronic Soundscapes 1961-88 (Various Artists)", "Carl Matthews - Call for World Saviours", "Stratis - New Face", "Beverly Glenn-Copeland", "Steven Halpern & Georgia Kelly - Ancient Echoes", "El disco de 2023 de Yves Tumor", "Gato - Chapter One: Latin America", "Igor Wakhevitch - Hathor", "Steve Maxwell von Braund - Monster Hunter", "Shadow - Sweet Sweet Dreams", "Brother Resistance - Rapso Takeover", "Flaming Tunes", "telepath dos chicas en la costa", "Talk Talk - The Party's Over", "Talk Talk - The Colour of Spring", "Public Image Ltd.", "PILtd. - Album", "Charles Hamilton - The Pink Lavalamp", "Charles Hamilton - Well Isn't This Awkward", "Donnie & Joe Emerson - Dreamin' Wild", "MSPaint - Post-american", "Lonnie Holley - Oh Me Oh My", "JPEGMAFIA & Danny Brown - Scaring the Hoes", "Eric Copeland - Hermaphrodite", "Weed - Deserve", "Cibo Matto - Stereotype A", "Cities Aviv - Working Title for...", "Laraaji, Vision Songs Vol. 1", "Nihiloxica", "The Sound of Siam", "Hell - Hell II", "The Black Keys - Rubber Factory", "Naked Flames - Miracle in Transit", "Alice Coltrane - World Galaxy", "Caetano Veloso - Transa", "Pere Ubu - The Modern Dance", "Kiko Dinucci - Cortes Curtos", "Late of the Pier - Fantasy Black Channel"] 

const pickSpotifyFourOne = SpotifyFourOne[Math.floor(Math.random()*SpotifyFourOne.length)]
console.log("Spotify [4.1] - - - >", pickSpotifyFourOne)

const pickSpotifyFourTwo = SpotifyFourTwo[Math.floor(Math.random()*SpotifyFourTwo.length)]
console.log("Spotify [4.2] - - - >", pickSpotifyFourTwo)

console.log(espacio)
console.log(espacio)

const SpotifyFiveOne = ["18 Carat Affair - Spent Passions 2", "Alchemist - Israeli Salad", "Andrew Bird - Are You Serious", "Antônio Carlos Jobim - Wave", "Arawak - Accadde a…", "The Arms of Someone New - Susan Sleepwalking", "Arzachel", "Asmus Tietchens - Nachtstücke", "Au Pairs - Playing With a Different Sex", "Baden Powell - Os Afro - Sambas De Baden E Vinícius", "Barbatos - Rocking Metal Motherfucker", "Berliner Philharmoniker - Albinoni", "Beverly Copeland (1970)", "The Black Keys - El Camino", "Brainstorm - Smile a While", "Caravan - In The Land Of Grey And Pink", "The Chemical Brothers - Exit Planet Dust", "Christoph De Babalon - If You're Into It I'm Out of It", "Chrome Canyon - Elemental Themes", "Coco Bryce - Night On Earth", "Congo Natty - Tribute To Haile Selassie I", "Cristina - Ze Debut Redux Album", "Daft Punk - Alive 1997", "Daft Punk - Alive 2007", "Death in June - Burial", "Dominique Guiot - L'univers De La Mer", "Donna Summer - Bad Girls", "Dubmood - Lost Floppies vol. 1", "ESPRIT 空想 - 200% Electronica", "Eyeliner - Drop Shadow", "farewell, alaska - piano songs", "FIRE-TOOLZ - Field Whispers (Into The Crystal Palace)", "fishpaste - stuck in the purple realm near the head of god", "Françoise Hardy - Soleil", "Françoise Hardy - Message personnel", "Françoise Hardy - Décalages", "Fripp & Eno - (No Pussyfooting)", "Fun Fun - Have Fun!", "Gal Costa - Gal Costa", "GAS - Zauberberg", "GAS - Königsforst", "GAS - Narkopop", "Grandaddy - The Sophtware Slump", "Grant Hart - Intolerance", "Guru Guru - UFO", "HALCALI BACON", "Haustor - Bolero", "Heavens to Betsy - Calculated", "Helen - The Original Faces", "Herbert von Karajan - New World Symphony / The Moldau", "Hiroshi Yoshimura - Music For Nine Post Cards", "Holger Czukay - Movies", "Hot Chip - The Warning", "HTRK - Psychic 9-5 Club", "Igor Stravinsky - Le Sacre du Printemps", "Ilkae - Pistachio Island", "Ithildin - Arda's Herbarium IV", "Jasmine Guffond - Traced", "Jennifer Walshe - A Late Anthology of Early Music, Vol. 1: Ancient to Renaissance", "John Cale - Fear", "John Cale - Artificial Intelligence", "Kano - Another Life", "Kara-Lis Coverdale - A 480", "Kevin Ayers - Joy Of A Toy", "KRYPTONYTE", "La Düsseldorf - Viva", "Las Manos De Filippi", "Leon Redbone - On the Track", "Lucid Express", "Herbert von Karajan - Symphony No.9", "Malo - Malo", "Jacob's Optical Stairway", "Matmos - The Rose Has Teeth in the Mouth of a Beast", "Michael Rother - Flammende Herzen", "Model/Actriz - Dogsbody"]

const SpotifyFiveTwo = ["Moebius - Rastakraut Pasta", "MOM$ - RAVE SHIT III: Tactical Operations", "Mighty Sparrow - Hot and Sweet", "Naked Flames - Miracle In Transit", "Odd Nosdam - Burner", "Peggy Lee - Black Coffee", "Perfume Genius - Ugly Season", "Pisse - Lambada", "Porter Ricks - Biokinetics", "Proxyon", "Psychic Mirrors - Ophilia", "Purple Motion - Musicdisk", "R. Crumb and His Cheap Suit Serenaders - Chasin' Rainbows", "Redshift", "Robert Mitchum - Calypso - Is Like So...!", "Rosal - Educación Sentimental", "Rx Papi & Gud - Foreign Exchange", "Ryoji Ikeda - Dataplex", "Ryuichi Sakamoto - 1996", "Sally Shapiro - Disco Romance", "Savage - Tonight", "Shitmat - One Foot in the Rave", "Shocking Blue - Scorpio's Dance", "Shuggie Otis - INSPIRATION INFORMATION", "Siekiera - Nowa Aleksandria", "Siouxsie and the Banshees - Juju", "Skinny Puppy - Mind: The Perpetual Intercourse", "Sparkling Wide Pressure - Grandfather Harmonic", "Spliff - 85555", "Ssleeping desiresS - Ssleeping Desiress", "Starflyer 59 - The Fashion Focus", "STORMKEEP - Tales of Othertime", "Sun Ra - Space Is The Place", "superpusssy - liquid paper", "Suzanne Ciani - Seven Waves", "Team Dresch - Captain My Captain", "Tan Biónica - Obsesionario", "Tek lintowe - My tek lintowe", "t e l e p a t h - 一緒に別の夜", "Television Personalities - And Don't the Kids Just Love It", "Thelonious Monk - Straight, No Chaser", "Thelonious Monk - Underground", "Thomas Barrandon - Escape from Earth", "Thom Brennan - Mist", "Thursar - Journey to Jotunheim", "Tonstartssbandht - An When", "Trust - TR/ST", "Vangelis - See You Later", "Vangelis - Heaven and Hell", "Vår - God Made Flesh", "Void Vision - Sub Rosa", "Will Powers - Dancing For Mental Health", "William Basinski - dlp IV", "William Basinski - Melancholia", "William Basinski - El Camino Real", "William Basinski - Selva Oscura", "Wintersleep - Dreams", "Wolfgang Bock - Cycles", "Young Fathers - Heavy Heavy", "假假條 - 時代在召喚", "Various Artists - Calypso and Meringues"]

const pickSpotifyFiveOne = SpotifyFiveOne[Math.floor(Math.random()*SpotifyFiveOne.length)]
console.log("Spotify [5.1] - - - >", pickSpotifyFiveOne)

const pickSpotifyFiveTwo = SpotifyFiveTwo[Math.floor(Math.random()*SpotifyFiveTwo.length)]
console.log("Spotify [5.2] - - - >", pickSpotifyFiveTwo)

console.log(espacio)
console.log(espacio)

const rym = ["A Tribe Called Quest - Midnight Marauders", "ABBA - Arrival", "Adele - 21", "AIR - Moon Safari", "Against All Logic - 2012-2017", "Agent Orange - Living in Darkness", "Alice Coltrane - Journey in Satchidananda", "Animal Collective - Strawberry Jam", "Animal Collective - Merriweather Post Pavillion", "Ankoku Tairiku Jagatara - Nanban torai", "Arcade Fire - Funeral", "Arctic Monkeys - Whatever People Say I Am...", "Arctic Monkeys - AM", "Autechre - Confield", "The Avalanches - Since I Left You", "Bauhaus - In the Flat Field", "Beach House - Depression Cherry", "Belle and Sebastian - If You're Feeling Sinister", "Billie Eilish - when we fall asleeep, where do we go?", "The Birthday Party - Junkyard", "Blur - Parklife", "Boards of Canada - Geogaddi", "Bob Dylan - Highway 61 Revisited", "Boris - Amplifier Worship", "Broadcast - Tender Buttons", "Cake - Fashion Nugget", "Cecilio.G - Million Dollar Baby", "Charles Mingus - The Clown", "Chet Baker Sings", "Coldplay - A Rush of Blood to the Head", "Comus - First Utterance", "Creedence Clearwater Revival - Willy and the Poor Boys", "Crystal Castles", "Darkthrone - A Blaze in the Northern Sky", "Darkthrone - Transilvanian Hunger", "David Bowie - Aladdin Sane", "David Bowie - Let's Dance", "David Bowie - Earthling", "Dinosaur Jr. - You're Living All Over Me", "The Doors - Strange Days", "Drive Like Jehu - Yank Crime", "Earth 2", "Einstürzende Neubauten alber Mensch", "Fiona Apple - Tidal", "FKA Twigs - Magdalene", "Franz Ferdinand", "Fugazi - The Argument", "George Harrison - All Things Must Pass", "Global Communication - 76:14", "Grouper - A I A", "Harry Styles - Fine Line", "Henry Cow Band (la media)", "Hijokaidan - King of Noise", "The House of Love" ,"Iggy Pop - Lust for Life", "Jawbreaker - Unfun", "Jimi Hendrix Trio - Axis: Bold as Love", "John Coltrane - Blue Train", "John Coltrane - Giant Steps", "Plastic Ono Band", "Baglietto - Tiempos Difíciles", "Kali Uchis (disco en donde está Telepatía)", "Kate Bush - The Kick Inside", "Kate Bush - The Sensual World", "King Krule - The Ooz", "The Kinks Are the Village Green Preservation Society", "The Kinks - Arthur or the Decline and Fall of the British Empire", "LCD Soundsystem - This is Happening", "Led Zeppelin - Houses of the Holy", "Leonard Cohen - Songs by Leonard Cohen", "Lil Ugly Mane - Three Sided Tape Vol. 1", "Lil Ugly Mane - Three Sided Tape Vol. 2", "Lil Ugly Mane - Three Sided Tape Vol. 3", "Lingua Ignota - Caligula"]

const rymDos = ["Spinetta - Mondo di Cromo", "Spinetta - Privé", "Mad Season - Above", "The Microphones - Mount Eerie", "Minutemen - Double Dickels on the Dime", "Mogwai - Mogwai Young Team", "Mogwai - Come On Die Young", "Mogwai - Happy Songs for Happy People", "Nancy Sinatra & Lee", "Negativland - Helter Stupid", "NEU! 2", "La! NEU? - Düsseldorf", "NIN - Pretty Hate Machine", "telepath (el disco verde agua con una catarata y la piba con poca opacidad)", "Niños del Cerro - Lance", "The Notorious B.I.G. - Ready to Die", "nouns - Still Bummed", "Pan Deijing", "Paul & Linda McCartney - Ram", "Peter Gabriel 1", "Peter Gabriel 3", "Peter Gabriel - So", "PJ Harvey - Rid of Me", "The Police - Synchronicity", "Pom Poko - Cheater", "Polvo - Today's Active Lifestyles", "R.E.M - Reckoning", "R.E.M - Lifes Rich Pageant", "R.E.M. - Green", "R.E.M. - Automatic for the People", "The Red Krayola", "The Residents - Not Available", "The Residents - Duck Stab", "Robert Wyatt - Rock Bottom", "Rolling Stones - Sticky Fingers", "Rosalía - El Mal Querer", "Röyksopp - Melody A.M.", "Rush - A Farewell to Kings", "Russian Ballet Troupe - Эта кошка ваша?", "Santana - Abraxas", "Santana III", "Scott Walker - Scott 4", "Sidney Gish - No Dogs Allowed", "Sky Ferreira - Night Time, My Time", "Slowdive - Pygmalion", "Sly & The Family Stone - There's a Riot Goin' On", "Sonic Youth - Daydream Nation", "Space Art - Trip in the Center Head", "Spinetta Jade - Bajo Belgrano", "Sufjan Stevens - Illinois", "Supercar - Three Out Change!!", "Swans - Children of God", "Swans - The Seer", "Talking Heads - True Stories", "Los Tres - Fome", "U2 - The Joshua Tree", "The Velvet Underground - White Light/White Heat", "The Weeknd - After Hours", "Ween - GodWeenSatan", "Yung Lean - Unknown Death 2002", "The Zombies - Odyssey & Oracle"]

const pickrym = rym[Math.floor(Math.random()*rym.length)]
console.log("RYM [1.1] - - - >", pickrym)

const pickrymDos = rymDos[Math.floor(Math.random()*rymDos.length)]
console.log("RYM [1.2] - - - >", pickrymDos)